# Generated by Django 3.2.8 on 2025-06-27 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrecord',
            options={},
        ),
        migrations.AddField(
            model_name='classrecord',
            name='custom_columns',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='spreadsheet_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='classrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classrecord',
            name='teacher',
        ),
    ]
