# Generated by Django 3.2.8 on 2025-06-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrecord', '0002_auto_20250627_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='excel_last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='imported_excel_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='imported_excel_headers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='imported_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='is_excel_imported',
            field=models.BooleanField(default=False),
        ),
    ]
