# Generated by Django 3.2.8 on 2025-06-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrecord', '0003_auto_20250627_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='google_sheet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='google_sheet_url',
            field=models.URLField(blank=True),
        ),
    ]
