# Generated by Django 3.2.8 on 2025-06-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrecord', '0004_auto_20250630_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='google_sheet_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
