# Generated by Django 3.2.8 on 2025-07-06 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrecord', '0005_alter_classrecord_google_sheet_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_id', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('excel_column_name', models.CharField(max_length=255)),
                ('target_column_name', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('import_session_id', models.CharField(max_length=100)),
                ('import_action', models.CharField(default='replace', max_length=20)),
                ('data_points_imported', models.IntegerField(default=0)),
                ('class_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_history', to='classrecord.classrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='columnimporthistory',
            index=models.Index(fields=['google_sheet_id', 'excel_column_name'], name='classrecord_google__d23bae_idx'),
        ),
        migrations.AddIndex(
            model_name='columnimporthistory',
            index=models.Index(fields=['class_record', 'imported_at'], name='classrecord_class_r_d39352_idx'),
        ),
    ]
