# Generated by Django 3.2.8 on 2025-09-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrecord', '0006_auto_20250707_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(choices=[('CLASS_STANDING', 'Class Standing')], default='CLASS_STANDING', max_length=64)),
                ('category_name', models.CharField(max_length=255)),
                ('percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_percentages', to='classrecord.classrecord')),
            ],
            options={
                'ordering': ['class_record_id', 'sheet_name', 'category_name'],
            },
        ),
        migrations.AddIndex(
            model_name='categorypercentage',
            index=models.Index(fields=['class_record', 'sheet_name', 'group'], name='classrecord_class_r_d27f32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorypercentage',
            unique_together={('class_record', 'sheet_name', 'category_name', 'group')},
        ),
    ]
