# Generated by Django 3.2.8 on 2025-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrecord', '0007_auto_20250929_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='completeness_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='completeness_sheet_version',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='grades_completeness',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
