# Generated by Django 3.2.8 on 2025-10-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrecord', '0008_auto_20251001_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrecord',
            name='completeness_checked_at',
        ),
        migrations.RemoveField(
            model_name='classrecord',
            name='completeness_sheet_version',
        ),
        migrations.RemoveField(
            model_name='classrecord',
            name='grades_completeness',
        ),
        migrations.AddField(
            model_name='classrecord',
            name='final_grade_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
