# Generated by Django 3.2.8 on 2025-10-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrecord', '0009_auto_20251012_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='section_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
