# Generated by Django 3.2.8 on 2025-10-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrecord', '0010_auto_20251024_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrecord',
            name='description',
        ),
    ]
