# Generated by Django 3.2.8 on 2025-12-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrecord', '0011_remove_classrecord_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
