apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vocalyx-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/vocalyx-backend
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DJANGO_SETTINGS_MODULE
          value: "backend.settings"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi