"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import dj_database_url
import firebase_admin
import json

from celery.schedules import crontab
from dotenv import load_dotenv
from firebase_admin import credentials

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-secret-key-for-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'


ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*', '10.0.165.206', '192.168.1.10', '.herokuapp.com', "192.168.254.101", '.run.app', '.googleapis.com']

# Firebase configuration - support both file and environment variable
FIREBASE_SERVICE_ACCOUNT_PATH = os.path.join(BASE_DIR.parent, 'firebase-service-account.json')

# Initialize Firebase Admin SDK with better error handling
if not firebase_admin._apps:
    firebase_initialized = False
    try:
        # First, try to use environment variable (for Cloud Run/Heroku)
        firebase_credentials_json = os.getenv('FIREBASE_SERVICE_ACCOUNT_KEY')
        if firebase_credentials_json:
            # Clean up JSON string
            firebase_credentials_json = firebase_credentials_json.strip()
            if firebase_credentials_json.startswith("'") and firebase_credentials_json.endswith("'"):
                firebase_credentials_json = firebase_credentials_json[1:-1]
            
            firebase_config = json.loads(firebase_credentials_json)
            cred = credentials.Certificate(firebase_config)
            firebase_admin.initialize_app(cred)
            firebase_initialized = True
            print("✅ Firebase Admin SDK initialized from environment variable")
        # Fall back to service account file (for local development)
        elif os.path.exists(FIREBASE_SERVICE_ACCOUNT_PATH):
            cred = credentials.Certificate(FIREBASE_SERVICE_ACCOUNT_PATH)
            firebase_admin.initialize_app(cred)
            firebase_initialized = True
            print("✅ Firebase Admin SDK initialized from service account file")
    except Exception as e:
        print(f"❌ Warning: Failed to initialize Firebase Admin SDK: {e}")
        firebase_initialized = False
    
    if not firebase_initialized:
        print(f"⚠️ Firebase service account not found. Checked:")
        print(f"   - Environment variable: FIREBASE_SERVICE_ACCOUNT_KEY")
        print(f"   - File path: {FIREBASE_SERVICE_ACCOUNT_PATH}")
        print("Firebase authentication features will be disabled")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_celery_beat',
    'corsheaders',
    'users.apps.UsersConfig',
    'drf_spectacular',
    'notifications',
    'classrecord',
    'speech_services',
    'token_management.apps.TokenManagementConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS must be at the top
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'token_management.authentication.CustomJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Vocalyx API',
    'DESCRIPTION': 'Vocalyx Best Capstone',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
    'PREPROCESSING_HOOKS': [],
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'CONTACT': {
        'name': 'Vaness Capuras',
        'email': 'vanesscapuras@gmail.com'
    },
}


#JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'USE_TZ': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'AUTH_COOKIE_SECURE': True,
    'AUTH_COOKIE_SAMESITE': 'None' if not DEBUG else 'Lax',
}


# CORS settings - DEVELOPMENT MODE
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for development
CORS_ALLOW_CREDENTIALS = True

# Explicitly allow common development origins
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://10.0.165.206:8080",
    "http://10.0.165.206",
    "https://vocalyx-frontend.vercel.app",
    "http://192.168.254.101:8000",
    "http://192.168.254.101"
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-google-access-token',
]

# Additional CORS settings
CORS_ALLOW_PRIVATE_NETWORK = True
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_EXPOSE_HEADERS = []

# Additional settings to ensure CORS on error responses
CORS_URLS_REGEX = r'^/api/.*$'

# Ensure CORS headers are sent on error responses too
CORS_ORIGIN_ALLOW_ALL = True  # Deprecated setting but sometimes needed
CORS_ALLOW_ALL_ORIGINS = True  # Ensure this is enabled

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.firebaseapp\.com$",
    r"^https://.*\.googleapis\.com$",
]

GOOGLE_OAUTH2_CLIENT_ID = os.getenv('GOOGLE_OAUTH2_CLIENT_ID')
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH2_CLIENT_SECRET')

# Google token encryption key (generate a new one for production)
GOOGLE_TOKEN_ENCRYPTION_KEY = os.getenv('GOOGLE_TOKEN_ENCRYPTION_KEY')

MICROSOFT_AUTH_CLIENT_ID = os.getenv('MICROSOFT_AUTH_CLIENT_ID')
MICROSOFT_AUTH_TENANT_ID = 'common'

MICROSOFT_AUTH_CLIENT_SECRET = os.getenv('MICROSOFT_AUTH_CLIENT_SECRET')

GOOGLE_APPLICATION_CREDENTIALS = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

#Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'sslmode': 'require',
        }
    }
}

# Override with DATABASE_URL if provided (for Heroku deployment)
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.parse(os.environ['DATABASE_URL'])


SECURE_SSL_REDIRECT = False if DEBUG else True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = False if DEBUG else True
CSRF_COOKIE_SECURE = False if DEBUG else True

# CSRF settings for development
if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_HTTPONLY = False

CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-tokens': {
        'task': 'token_management.tasks.cleanup_expired_tokens',
        'schedule': crontab(hour= '0', minute= '0'),
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.CustomUser'

# Google Sheets Template Configuration
GOOGLE_SHEETS_TEMPLATE_ID = os.getenv('GOOGLE_SHEETS_TEMPLATE_ID', '1h-dR0ergnvgqxXsS6nLFb7lAthuoJ5MVKya4NbYHT2c')

# Google API Key for public sheet access (fallback when user auth fails)
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')

# Load Google Service Account Credentials - improved error handling
GOOGLE_SERVICE_ACCOUNT_CREDENTIALS = {}
SERVICE_ACCOUNT_FILE = os.path.join(BASE_DIR.parent, 'vocalyx2-service-account.json')

# Try to load from environment variable first (for Cloud Run/Heroku)
google_service_account_json = os.getenv('GOOGLE_SERVICE_ACCOUNT_CREDENTIALS')
google_service_loaded = False

if google_service_account_json:
    try:
        # Clean up the JSON string - remove any extra escaping
        google_service_account_json = google_service_account_json.strip()
        if google_service_account_json.startswith("'") and google_service_account_json.endswith("'"):
            google_service_account_json = google_service_account_json[1:-1]
        
        GOOGLE_SERVICE_ACCOUNT_CREDENTIALS = json.loads(google_service_account_json)
        
        # Verify the required fields are present
        required_fields = ['type', 'project_id', 'private_key_id', 'private_key', 'client_email']
        missing_fields = [field for field in required_fields if field not in GOOGLE_SERVICE_ACCOUNT_CREDENTIALS]
        
        if missing_fields:
            raise ValueError(f"Missing required fields: {missing_fields}")
            
        # Verify the private key format
        private_key = GOOGLE_SERVICE_ACCOUNT_CREDENTIALS.get('private_key', '')
        if '-----BEGIN PRIVATE KEY-----' not in private_key:
            raise ValueError("Invalid private key format")
            
        google_service_loaded = True
        print("✅ Google Service Account credentials loaded from environment variable")
        
    except (json.JSONDecodeError, ValueError) as e:
        print(f"❌ Error parsing Google Service Account credentials from environment: {e}")
        print("🔧 Falling back to file or disabling Google Sheets features")
        GOOGLE_SERVICE_ACCOUNT_CREDENTIALS = {}

# Fall back to file (for local development) if env loading failed
if not google_service_loaded:
    if os.path.exists(SERVICE_ACCOUNT_FILE):
        try:
            with open(SERVICE_ACCOUNT_FILE, 'r') as f:
                GOOGLE_SERVICE_ACCOUNT_CREDENTIALS = json.load(f)
            google_service_loaded = True
            print(f"✅ Google Service Account credentials loaded from {SERVICE_ACCOUNT_FILE}")
        except Exception as e:
            print(f"❌ Error loading service account file: {e}")
    
    # Also check in current directory as fallback
    if not google_service_loaded:
        current_service_file = os.path.join(BASE_DIR, 'vocalyx2-service-account.json')
        if os.path.exists(current_service_file):
            try:
                with open(current_service_file, 'r') as f:
                    GOOGLE_SERVICE_ACCOUNT_CREDENTIALS = json.load(f)
                google_service_loaded = True
                print(f"✅ Google Service Account credentials loaded from {current_service_file}")
            except Exception as e:
                print(f"❌ Error loading service account file from current directory: {e}")

# Final fallback message if nothing worked
if not google_service_loaded:
    print(f"❌ Warning: Google Service Account credentials not found")
    print(f"   - Environment variable: GOOGLE_SERVICE_ACCOUNT_CREDENTIALS")
    print(f"   - File path: {SERVICE_ACCOUNT_FILE}")
    print(f"   - Current directory: {os.path.join(BASE_DIR, 'vocalyx2-service-account.json')}")
    print("🔧 Google Sheets integration will be disabled")