# Generated by Django 3.2.8 on 2025-05-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20250516_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Mid Year', 'Mid Year')], max_length=100),
        ),
    ]
