# Generated by Django 3.2.8 on 2025-03-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_microsoft_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='custom_users',
        ),
    ]
