# Generated by Django 3.2.8 on 2025-05-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.CharField(default='Cebu Institute of Technology - University', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='Teacher/Instructor', max_length=255),
        ),
    ]
