# Generated by Django 3.2.8 on 2025-07-03 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250516_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('record_created', 'Created Class Record'), ('record_updated', 'Updated Class Record'), ('record_deleted', 'Deleted Class Record'), ('record_viewed', 'Viewed Class Record'), ('voice_command', 'Used Voice Command'), ('batch_grading', 'Performed Batch Grading'), ('student_added', 'Added Student'), ('student_updated', 'Updated Student'), ('grade_updated', 'Updated Grade'), ('export_excel', 'Exported to Excel'), ('export_pdf', 'Exported to PDF'), ('sheet_switched', 'Switched Sheet'), ('bulk_import', 'Imported Bulk Data'), ('auto_number', 'Auto-numbered Students'), ('profile_updated', 'Updated Profile')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('class_record_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-created_at'], name='user_activi_user_id_47a698_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='user_activi_activit_b9defd_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['class_record_id', '-created_at'], name='user_activi_class_r_6da859_idx'),
        ),
    ]
