# Generated by Django 3.2.8 on 2025-02-16 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('blacklisted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['token'], name='token_manag_token_d1a3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['expires_at'], name='token_manag_expires_cce811_idx'),
        ),
    ]
