# Generated by Django 3.2.8 on 2025-03-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blacklistedtoken',
            name='token_manag_token_d1a3a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='blacklistedtoken',
            name='token_manag_expires_cce811_idx',
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['token'], name='token_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['expires_at'], name='expires_idx'),
        ),
        migrations.AlterModelTable(
            name='blacklistedtoken',
            table='blacklisted_tokens',
        ),
    ]
