# Generated by Django 3.2.8 on 2025-04-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='sheet_data',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ExcelData',
        ),
    ]
