# Generated by Django 3.2.8 on 2025-05-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('excel', '0002_auto_20250407_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='class_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_files', to='classes.class'),
        ),
    ]
