# Generated by Django 3.2.8 on 2025-05-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_excelfile_class_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='sheet_data',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='active_sheet',
            field=models.CharField(default='Sheet1', max_length=255),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='all_sheets',
            field=models.JSONField(default=dict),
        ),
    ]
