# Generated by Django 3.2.8 on 2025-05-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_auto_20250519_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='category_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
