# Generated by Django 3.2.8 on 2025-05-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_auto_20250519_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='update_count',
            field=models.IntegerField(default=0),
        ),
    ]
